In [1]:
import pandas as pd
# with open('euro2012.csv', 'r') as file:
    # euro12 = pd.read_csv(file)
euro12 = pd.read_csv('euro2012.csv')
print(type(euro12))
print(euro12.shape)
print(euro12.columns.tolist())

<class 'pandas.core.frame.DataFrame'>
(16, 36)
['Unnamed: 0', 'Team', 'Goals', 'Shots on target', 'Shots off target', 'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)', 'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals', 'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses', 'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions', 'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded', 'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded', 'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off', 'Players Used']

In [2]:
# 1
print(euro12['Goals'])

0      4
1      4
2      4
3      5
4      3
5     10
6      5
7      6
8      2
9      2
10     6
11     1
12     5
13    12
14     5
15     2
Name: Goals, dtype: int64

In [3]:
# 2
print("số đội tham gia euro 2012 là:",len(euro12))

số đội tham gia euro 2012 là: 16

In [4]:
# 3
print(euro12)

    Unnamed: 0                 Team  Goals  Shots on target  Shots off target  \
0            0              Croatia      4               13                12
1            1       Czech Republic      4               13                18
2            2              Denmark      4               10                10
3            3              England      5               11                18
4            4               France      3               22                24
5            5              Germany     10               32                32
6            6               Greece      5                8                18
7            7                Italy      6               34                45
8            8          Netherlands      2               12                36
9            9               Poland      2               15                23
10          10             Portugal      6               22                42
11          11  Republic of Ireland      1                7                12
12          12               Russia      5                9                31
13          13                Spain     12               42                33
14          14               Sweden      5               17                19
15          15              Ukraine      2                7                26

   Shooting Accuracy % Goals-to-shots  Total shots (inc. Blocked)  \
0             51.90%           16.00%                          32
1             41.90%           12.90%                          39
2             50.00%           20.00%                          27
3             50.00%           17.20%                          40
4             37.90%            6.50%                          65
5             47.80%           15.60%                          80
6             30.70%           19.20%                          32
7             43.00%            7.50%                         110
8             25.00%            4.10%                          60
9             39.40%            5.20%                          48
10            34.30%            9.30%                          82
11            36.80%            5.20%                          28
12            22.50%           12.50%                          59
13            55.90%           16.00%                         100
14            47.20%           13.80%                          39
15            21.20%            6.00%                          38

    Hit Woodwork  Penalty goals  ...  Saves made  Saves-to-shots ratio  \
0              0              0  ...          13                81.30%
1              0              0  ...           9                60.10%
2              1              0  ...          10                66.70%
3              0              0  ...          22                88.10%
4              1              0  ...           6                54.60%
5              2              1  ...          10                62.60%
6              1              1  ...          13                65.10%
7              2              0  ...          20                74.10%
8              2              0  ...          12                70.60%
9              0              0  ...           6                66.70%
10             6              0  ...          10                71.50%
11             0              0  ...          17                65.40%
12             2              0  ...          10                77.00%
13             0              1  ...          15                93.80%
14             3              0  ...           8                61.60%
15             0              0  ...          13                76.50%

    Fouls Won  Fouls Conceded Offsides  Yellow Cards  Red Cards  Subs on  \
0          41              62        2             9          0        9
1          53              73        8             7          0       11
2          25              38        8             4          0        7
3          43              45        6             5          0       11
4          36              51        5             6          0       11
5          63              49       12             4          0       15
6          67              48       12             9          1       12
7         101              89       16            16          0       18
8          35              30        3             5          0        7
9          48              56        3             7          1        7
10         73              90       10            12          0       14
11         43              51       11             6          1       10
12         34              43        4             6          0        7
13        102              83       19            11          0       17
14         35              51        7             7          0        9
15         48              31        4             5          0        9

    Subs off  Players Used
0          9            16
1         11            19
2          7            15
3         11            16
4         11            19
5         15            17
6         12            20
7         18            19
8          7            15
9          7            17
10        14            16
11        10            17
12         7            16
13        17            18
14         9            18
15         9            18

[16 rows x 36 columns]

In [5]:
# 4
discripline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
discripline

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [6]:
# 5
discripline = discripline.sort_values(['Red Cards', 'Yellow Cards'], ascending=[False, False])
discripline

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

In [7]:
# 6
# a
print("trung bình Yellow Cards:",euro12['Yellow Cards'].mean())
# b
print("các đội đã ghi hơn 6 bàn thắng:\n",euro12[euro12['Goals'] > 6]['Team'])

trung bình Yellow Cards: 7.4375
các đội đã ghi hơn 6 bàn thắng:
 5     Germany
13      Spain
Name: Team, dtype: object

In [8]:
# 7
print(euro12[euro12['Team'].str.startswith('G')]['Team'])

5    Germany
6     Greece
Name: Team, dtype: object

In [9]:
# 8
print(euro12.iloc[:,:7])

    Unnamed: 0                 Team  Goals  Shots on target  Shots off target  \
0            0              Croatia      4               13                12
1            1       Czech Republic      4               13                18
2            2              Denmark      4               10                10
3            3              England      5               11                18
4            4               France      3               22                24
5            5              Germany     10               32                32
6            6               Greece      5                8                18
7            7                Italy      6               34                45
8            8          Netherlands      2               12                36
9            9               Poland      2               15                23
10          10             Portugal      6               22                42
11          11  Republic of Ireland      1                7                12
12          12               Russia      5                9                31
13          13                Spain     12               42                33
14          14               Sweden      5               17                19
15          15              Ukraine      2                7                26

   Shooting Accuracy % Goals-to-shots
0             51.90%           16.00%
1             41.90%           12.90%
2             50.00%           20.00%
3             50.00%           17.20%
4             37.90%            6.50%
5             47.80%           15.60%
6             30.70%           19.20%
7             43.00%            7.50%
8             25.00%            4.10%
9             39.40%            5.20%
10            34.30%            9.30%
11            36.80%            5.20%
12            22.50%           12.50%
13            55.90%           16.00%
14            47.20%           13.80%
15            21.20%            6.00%

In [ ]:
# 9
print(euro12.iloc[:,:-3])

In [ ]:
# 10
print(euro12[['Team','Goals','Shooting Accuracy','Yellow Cards','Red Cards']])

In [ ]:
# 11
print(euro12.loc[euro12['Team'].isin(['England','Italy','Russia']),['Team','Shooting Accuracy']])